### PR TITLE
Added feature to support custom external filters

### PR DESCRIPTION
**Pull request by KansaraMaulik**
Added feature to support custom external filters.

User can create CustomFilter Dictionary and can bind to control using CustomFilters={Binding [Dictionary]};

### CODE REVIEW

**Comment by macgile** [comment]
Hi,
I have just tested your solution for customFilter, it works well, however I don't see what more it brings compared to a filter applied to the collection before feeding the FilterDataGrid.

**Comment by macgile** [comment]
It is also possible that I have misunderstood your solution.
best regards

**Comment by macgile** [comment]
Hi KansaraMaulik,

Don't think I forgot your contribution, your code offers an interesting approach that could be used for another feature not yet implemented.
I therefore do not validate the pull request because as I told you, it seems simpler to me to do a "linq" query on the source collection of the datagrid, this seems simpler to implement for a beginner developer .
When I use your code I will be sure to let you know.

Best regard

**Comment by KansaraMaulik** [comment]
Hi macgile,

Apologies for late response.

Its ok not to include the pull request.

my scenario was completely different. Actually, i am working on trading app where i am using filter data grid to show traded orders. Here, orders can be confirmed/rejected this status field is not visible on the grid so end user will not be able to filter. And it is not possible to use linq query on order record update. So, I was looking for an external filter.

thank you for allocating your time to review the work. Appreciated !!

**Pull request closed without merging**
