### PR TITLE
feat: add permanent filters

### LINKED ISSUE #108: Feature request: Saving and resetting filters
Hi all,

I am working on a project, where it would be nice to save the filters that are currently selected. I can then save and load filter presets, which is nice to have in certain use-cases.

Currently, it was easy to get the filters by creating a public property for the criteria list. But when I try to set the criteria list again. It is not updating all the filters and the view again. Can anybody help me with this implementation?

Currently, I edited something like this in the `Filterdatagrid.cs`:
```cs
public Dictionary<string, Predicate<object>> Filters
{
    get => criteria;
    set
    {
        // reset criteria List
        criteria.Clear();
        GlobalFilterList.Clear();
        
        criteria = value;

        CollectionViewSource = System.Windows.Data.CollectionViewSource.GetDefaultView(ItemsSource);
        if (CollectionViewSource.CanFilter) CollectionViewSource.Filter = Filter;
        CollectionViewSource.Refresh();


        OnPropertyChanged(nameof(Filters));
    }
}
```
I can get the filters by requesting `FilterDataGrid.Filters`, but when setting, it will not work.

### PR DESCRIPTION
**Pull request by BEDIRHANSAMSA**
Closes #108

### CODE REVIEW

**Comment by BEDIRHANSAMSA** [comment]
I think it's a good start, so the developer can specify it or bind it with Binding. Right now I'm just thinking about how to hook it up to our code. Do you have any ideas?

**Comment by ericvdberge** [comment]
When I try to bind the PermanentFilters property to a ModelView.cs Property,
mainwindow.xaml =>  PermanentFilters="{Binding FilterPreset, UpdateSourceTrigger=PropertyChanged}"
ModelView.cs => The property is created like this:  public Dictionary<string, Predicate<object>> FilterPreset { get; set; }
 I get the following error:
`Object of type 'System.Windows.Data.Binding' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.Predicate`1[System.Object]]'. MainWindow.xaml	98`	
Do you know the problem?

**Comment by BEDIRHANSAMSA** [comment]
> When I try to bind the PermanentFilters property to a ModelView.cs Property, mainwindow.xaml => PermanentFilters="{Binding FilterPreset, UpdateSourceTrigger=PropertyChanged}" ModelView.cs => The property is created like this: public Dictionary<string, Predicate> FilterPreset { get; set; } I get the following error: `Object of type 'System.Windows.Data.Binding' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.String,System.Predicate`1[System.Object]]'. MainWindow.xaml 98` Do you know the problem?

Currently only in the idea stage, the code will not work.

**Comment by ericvdberge** [comment]
@BEDIRHANSAMSA, sorry for the misunderstanding. Idea looks good. I will try to help find a solution for it.

**Comment by ericvdberge** [comment]
I made a pull request as well with promising results, maybe we can look into that? I made something work, The only thing what we need to do is to make an applyAllFilters command that applies all filters at once.

**Comment by ericvdberge** [comment]
I created #115, which closes #108. I think I solved it.

**Comment by macgile** [comment]
this request is duplicated with request [#115](https://github.com/macgile/DataGridFilter/issues/115)

**Pull request closed without merging**
