### PR TITLE
Feature: filter preset

### LINKED ISSUE #108: Feature request: Saving and resetting filters
Hi all,

I am working on a project, where it would be nice to save the filters that are currently selected. I can then save and load filter presets, which is nice to have in certain use-cases.

Currently, it was easy to get the filters by creating a public property for the criteria list. But when I try to set the criteria list again. It is not updating all the filters and the view again. Can anybody help me with this implementation?

Currently, I edited something like this in the `Filterdatagrid.cs`:
```cs
public Dictionary<string, Predicate<object>> Filters
{
    get => criteria;
    set
    {
        // reset criteria List
        criteria.Clear();
        GlobalFilterList.Clear();
        
        criteria = value;

        CollectionViewSource = System.Windows.Data.CollectionViewSource.GetDefaultView(ItemsSource);
        if (CollectionViewSource.CanFilter) CollectionViewSource.Filter = Filter;
        CollectionViewSource.Refresh();


        OnPropertyChanged(nameof(Filters));
    }
}
```
I can get the filters by requesting `FilterDataGrid.Filters`, but when setting, it will not work.

### PR DESCRIPTION
**Pull request by ericvdberge**
closes #108 with working prototype. 

**advantages:** 
- I have example code in the image below that works using a jsonserializer.
[Imgur image](https://imgur.com/l2ozQbK)
The button `Button_Write_Click` saves the filterpreset to a json file and the `Button_Read_Click` reads the filterpreset from the json file and applies it on the datagrid.

**disadvantages**:
- the package will depend on `Newtonsoft.json`, because we need `[JsonIgnore]` attributes on the FilterCommon class

**video:**
you can watch the video of how it works here:
- https://youtu.be/1Box0_oVUJo
- it waits for 5 seconds before it filters, so it is not slow even though it looks like

### CODE REVIEW

**Comment by macgile** [comment]
Hello Ericvdberge,

Thank you for having taken into account the recommendation not to use an external dependency, your code advantageously replaces the use of this one.
However, please note that the version on which you developed the "filter preset" functionality is deprecated since the integration of nested object support (1.2.8).
I won't make any further changes until your solution has matured.

best regards

**Comment by ericvdberge** [comment]
@macgile, yes it is hard to make something work. Normally, you would use the namespace `System.Text.Json.JsonSerializer`, because it is an internal class within c# to serialize and deserialize objects into json format and the other way arround. The problem I encounter, is that this is not supported by .net framework. At that time, it was not included into c#. I am searching for a solution to work, but it takes some time i guess

**Comment by BEDIRHANSAMSA** [comment]
@ericvdberge I think we should remove JSON Load & Save feature, developer can handle this feature himself. It might be enough if we just add a feature to set the filter. what are you thinking?

**Comment by ericvdberge** [comment]
Hi @BEDIRHANSAMSA, I think this is not possible, or we should adapt the FilterCommon class. 
1. I think no one is going to set a filterpreset from memory (without saving a preset to a file)
2. The filtercommon class is not serializable, because it has properties like `public Type FieldType { get; set; }` or `public PropertyInfo FieldProperty { get; set; }`. These properties are not serializable. someone that wants to save the preset to a file does not know the contents of the filtercommon class, and needs to guess which properties to serialize? I think that is not really a solid solution.

I agree that we should not make a feature to save it in a certain format, but I think that we at least should make it possible to json serialize the preset. What I mean by that is that we should make the class serializable, but not make the feature to save it (if you understand what I try to say here)

Do you agree?

**Pull request closed without merging**
